import { CHARACTERS } from "./simulation";
import { MAPS } from "./maps";

const coil = `<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M29 11C12-1 1 25 16 30c13 5 23-11 12-17-8-4-15 8-7 11" stroke="currentColor" stroke-width="4.5" stroke-linecap="round"/><circle cx="29" cy="11" r="3" fill="currentColor"/></svg>`;
const brand = `<div class="brand">${coil}<span>anime<span class="brand-coil">coil</span><small>CHARACTER SELECT · v1.6.7</small></span></div>`;
const settingsIcon = `<svg class="settings-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M10 2h4l.5 2.2 1.7.7 1.9-1.2 2.8 2.8-1.2 1.9.7 1.7L22 10v4l-2.2.5-.7 1.7 1.2 1.9-2.8 2.8-1.9-1.2-1.7.7L14 22h-4l-.5-2.2-1.7-.7-1.9 1.2-2.8-2.8 1.2-1.9-.7-1.7L2 14v-4l2.2-.5.7-1.7-1.2-1.9 2.8-2.8 1.9 1.2 1.7-.7L10 2zM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>`;
const tools = `<button class="icon-button challenges-open" aria-label="Challenges and cosmetics" title="Challenges and cosmetics">✦</button><button class="icon-button help-open" aria-label="How to play" title="How to play">?</button><button class="icon-button settings-open" aria-label="Settings" title="Settings">${settingsIcon}</button>`;
export const ui = `
<canvas id="world" aria-label="3D spirit serpent arena"></canvas>
<canvas id="boost-speed-lines" aria-hidden="true"></canvas>
<div id="kill-stamps" aria-hidden="true"></div>
<div id="skill-visual" hidden role="status" aria-live="polite"><strong id="skill-japanese" lang="ja"></strong><span id="skill-label" lang="ja"></span></div>
<div id="cinematic" hidden aria-live="polite"><div class="cinema-dim"></div><div class="spirit-impact-art" aria-hidden="true"><div class="spirit-ink-rays"></div><div class="spirit-ink-contour"></div><div class="spirit-ink-core"></div></div><div class="fox-impact-art" aria-hidden="true"><div class="fox-ink-rays"></div>${Array.from({length:9},(_,i)=>`<i class="fox-ink-tail" style="--tail-angle:${i*40}deg"></i>`).join('')}<div class="fox-ink-beast"></div><div class="fox-ink-core"></div></div><div class="purple-impact-art" aria-hidden="true"><div class="purple-ink-rifts"></div><div class="purple-ink-left"></div><div class="purple-ink-right"></div><div class="purple-ink-cavity"></div><div class="purple-ink-core"></div></div><div class="skybreaker-impact-art" aria-hidden="true"><div class="skybreaker-ink-rays"></div><div class="skybreaker-ink-arm"></div><div class="skybreaker-ink-fist"></div><div class="skybreaker-ink-dent"></div><div class="skybreaker-ink-core"></div></div><div class="cinema-top"></div><div class="purple-flare"></div><div class="cinema-title"><small id="cinema-stage"></small><strong id="cinema-name">Hollow Purple</strong><span id="cinema-caption" lang="ja"></span></div><div class="cinema-bottom"></div></div>
<main id="menu"><header class="topbar">${brand}<nav aria-label="Game tools">${tools}</nav></header>
<section class="menu-content"><div class="selection-panel">
<div class="panel-heading"><span class="leaf" aria-hidden="true">✿</span><h1>Choose your character</h1></div>
<div class="characters" role="group" aria-label="Choose your character">${CHARACTERS.map((c, i) => `<button class="character" data-character="${c.id}" aria-label="Select ${c.name}" aria-pressed="${i === 0}"><img id="portrait-${c.id}" alt="${c.name}"><span class="selected-mark" aria-hidden="true">✓</span></button>`).join("")}</div>
<div class="selected-spirit"><h2 id="hero-name">Kitsu</h2><span class="skill-badge"><kbd id="menu-ability-key">E</kbd><span id="power-name">Fox Rush</span></span><span id="purple-badge" class="skill-badge purple" hidden><kbd id="menu-ultimate-key">V</kbd><span id="ultimate-badge-name">Hollow Purple</span></span></div>
<div class="section-label"><h3>A little change of scenery</h3><span aria-hidden="true">↗</span></div>
<div class="maps" role="group" aria-label="Choose your map">${MAPS.map((m) => `<button class="map-card" data-map="${m.id}" aria-label="Select ${m.name}" aria-pressed="false"><img id="map-${m.id}" alt="${m.name}"><span>${m.shortName}</span></button>`).join("")}</div>
<div class="mode-picker" role="group" aria-label="Match mode"><button class="mode-choice" data-mode="endless" aria-pressed="true">Endless</button><button class="mode-choice" data-mode="sprint" aria-pressed="false">3-Min Sprint</button><button class="mode-choice" data-mode="bounty" aria-pressed="false">Bounty Hunt</button></div>
<button id="play" class="play-button">Let's play <span aria-hidden="true">↗</span></button>
<div class="best"><span aria-hidden="true">✦</span> <span id="best-label">Personal best</span> <b id="best-score">0</b></div>
</div><div class="preview-label"><span aria-hidden="true">⌁</span><span id="map-preview-name">Shibuya After Dark</span></div><section id="skin-preview-controls" class="skin-preview-controls" aria-label="Snake skin preview" hidden><strong id="skin-preview-name"></strong><p id="skin-preview-detail" aria-live="polite"></p><div><button id="skin-preview-back" class="secondary-button">Back to skins</button><button id="skin-preview-equip" class="secondary-button">Equip skin</button></div></section></section>
<footer class="menu-footer"><button class="text-button credits-open">Credits</button></footer></main>
<div id="death-wash" aria-hidden="true"></div>
<section id="hud" hidden aria-label="Match status"><div class="hud-top"><div class="hud-score"><small id="score-label">Energy</small><strong id="score">180</strong><div class="stat-line"><span id="rank">#21</span> / <span id="population">21</span> · <span id="time">0:00</span></div><span id="hud-mode" aria-label="Endless mode">ENDLESS</span><span id="bounty-target" hidden aria-live="polite"></span></div><div class="hud-right"><div class="leaderboard"><h3>Top spirits <span>✦</span></h3><div id="leaders"></div></div><div class="hud-actions"><button class="icon-button settings-open" aria-label="Settings">${settingsIcon}</button><button id="pause" class="icon-button" aria-label="Pause game">Ⅱ</button></div></div></div><div id="toast" hidden role="status"></div><div id="unlock-notice" hidden role="status" aria-live="polite"></div><div id="bounty-world-marker" hidden aria-hidden="true">✦</div><div id="death-contact" hidden aria-hidden="true"></div><section id="respawn-notice" class="respawn-notice" hidden role="status" aria-live="polite" aria-label="Spirit resting. Respawn countdown"><span class="resting-flower" aria-hidden="true">☁</span><h2>Spirit resting</h2><p id="respawn-reason"></p><span id="respawn-count-label" class="respawn-count-label">Returning in</span><strong id="respawn-count">3</strong><span id="respawn-units" class="respawn-seconds">seconds</span></section><div class="hud-bottom"><div class="mini-wrap"><canvas id="minimap" width="240" height="240" role="img" aria-label="Spirit compass: your arrow, rival dots, and arena boundary"></canvas></div><div class="abilities"><button id="boost" class="ability-button boost-button"><strong>Boost</strong><small id="boost-status">Hold</small><kbd>Space</kbd></button><button id="ability" class="ability-button"><strong id="ability-name">Fox Rush</strong><small id="ability-status">Ready</small><kbd>E</kbd><span class="cool-fill" id="cool-fill"></span></button><button id="nuke" hidden class="ability-button nuke-button"><strong id="ultimate-name">Hollow Purple</strong><small id="nuke-status">Ready</small><kbd>V</kbd><span class="cool-fill" id="nuke-fill"></span></button></div></div><div class="joystick" id="joystick" aria-label="Steering joystick"><span id="stick"></span></div><section id="practice-guide" hidden aria-label="Guided practice"><b id="practice-step">Step 1 / 4</b><span id="practice-instruction" aria-live="polite"></span><small id="practice-detail"></small><div><button id="practice-skip" class="secondary-button">Skip step</button><button id="practice-exit" class="secondary-button">Leave practice</button></div></section></section>
<section id="pause-modal" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="pause-title"><div class="modal-card pause-card">
  <div class="modal-flower" aria-hidden="true">☁</div><h2 id="pause-title">A little breather.</h2><p>Your adventure can wait.</p>
  <button id="resume" class="play-button">Keep playing <span aria-hidden="true">↗</span></button>
  <div class="pause-tools">${tools}</div>
  <div class="pause-actions"><button id="end-recap" class="secondary-button">End run &amp; recap</button><button id="quit" class="secondary-button quiet-button">Back to the garden</button></div>
</div></section>
<section id="results" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="results-title"><div class="modal-card results-card">
  <div class="modal-header"><span class="sheet-icon" aria-hidden="true">✿</span><h2 id="results-title">One more adventure?</h2></div>
  <div class="modal-scroll"><p id="death-reason"></p><p id="result-record" class="result-record"></p>
    <div class="results-grid"><div><strong id="result-score">0</strong><small id="result-score-label">Best energy</small></div><div><strong id="result-time">0:00</strong><small>Survival</small></div><div><strong id="result-kills">0</strong><small>Eliminations</small></div></div>
    <p id="bounty-results" hidden></p><p id="session-progress" class="session-progress"></p><p id="session-unlocks" class="session-unlocks"></p>
    <div class="result-actions"><button id="restart" class="play-button">Play again <span aria-hidden="true">↗</span></button><button id="result-challenges" class="secondary-button challenges-open">View challenges</button><button id="change" class="secondary-button quiet-button">Choose a spirit</button></div>
  </div>
</div></section>
<dialog id="help-dialog" class="sheet" aria-labelledby="help-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">?</span><h2 id="help-title">A tiny field guide</h2><button class="close-button" aria-label="Close help">×</button></div>
  <div class="sheet-scroll"><p class="help-intro">Gather energy to grow. Steer clear of rival heads, coils, and the arena edge. Your own tail is safe.</p>
    <div class="control-guide"><span><kbd>Mouse</kbd><span>Steer</span></span><span><kbd id="help-boost-key">Space</kbd><span>/ click Boost · spends energy</span></span><span><kbd id="help-ability-key">E</kbd><span>/ right-click Skill</span></span><span><kbd id="help-ultimate-key">V</kbd><span>Cinematic ultimate</span></span><span><kbd>Esc</kbd><span>Pause</span></span></div>
    <p class="touch-guide">On touch screens, use the joystick and skill buttons.</p><button id="practice-start" class="secondary-button practice-button">Try guided practice</button>
    <details class="help-details"><summary>Match modes</summary><p>In Bounty Hunt, collect naturally spawned orbs and defeat the marked rival for points and ultimate charge. Ultimate KOs count as KOs but give no Bounty points or charge.</p></details>
    <details class="help-details"><summary>Character skills · E</summary><div class="help-skills">${CHARACTERS.map((c) => `<article><h3>${c.name}<span>${c.cooldown}s cooldown</span></h3><p><b>${c.power}.</b> ${c.description}</p></article>`).join("")}</div></details>
    <details class="help-details"><summary>Cinematic ultimates · V</summary><div class="help-skills"><article><h3>Kitsu: Fox Spirit Bomb <span>V · 5.6s · 30s cooldown</span></h3><p>Summon a giant fox spirit to charge and fire an arena-wide bomb. Rivals freeze in place, you stay safe, and bots return after the blast. Fox Rush remains your E skill.</p></article><article><h3>Pomu: Skybreaker Slam <span>V · 5.6s · 30s cooldown</span></h3><p>Transform and wind up a giant cartoon fist, then slam the arena. Rivals freeze in place until the impact; every rival falls and returns after the blast.</p></article><article><h3>Hollow Purple <span>V · 5.6s · 30s cooldown</span></h3><p>Shiro's cinematic ultimate pulls in every rival before the blast. You stay safe; every rival falls. New bots appear afterward.</p></article><article><h3>Spirit Bomb <span>V · 5.6s · 30s cooldown</span></h3><p>Kairo freezes rivals in place, gathers energy overhead, and throws a giant Spirit Bomb that wipes the arena clean. You stay safe; bots return after the blast.</p></article></div></details>
  </div>
</dialog>
<dialog id="settings-dialog" class="sheet settings-sheet" aria-labelledby="settings-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">⚙</span><h2 id="settings-title">Settings</h2><button class="close-button" aria-label="Close settings">×</button></div>
  <div class="settings-tabs" role="tablist" aria-label="Settings sections">
    <button id="settings-tab-controls" role="tab" aria-selected="true" aria-controls="settings-panel-controls" tabindex="0" data-settings-tab="controls">Controls</button>
    <button id="settings-tab-appearance" role="tab" aria-selected="false" aria-controls="settings-panel-appearance" tabindex="-1" data-settings-tab="appearance">Appearance</button>
    <button id="settings-tab-audio" role="tab" aria-selected="false" aria-controls="settings-panel-audio" tabindex="-1" data-settings-tab="audio">Audio</button>
    <button id="settings-tab-accessibility" role="tab" aria-selected="false" aria-controls="settings-panel-accessibility" tabindex="-1" data-settings-tab="accessibility">Accessibility</button>
  </div>
  <div class="sheet-scroll settings-scroll">
    <section id="settings-panel-controls" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-controls" tabindex="0"><h3>Controls</h3><div class="binding-list">${(["boost","ability","ultimate"] as const).map(action => `<button class="secondary-button key-binding" data-action="${action}" aria-label="Change ${action} key"><span>${action}</span><kbd></kbd></button>`).join("")}</div><p id="binding-note" role="status">Select a control, then press a letter, number, or Space.</p><h4>Touch layout</h4><div class="setting-choices" role="group" aria-label="Touch handedness"><button class="secondary-button touch-hand-choice" data-hand="left" aria-pressed="true">Left steer</button><button class="secondary-button touch-hand-choice" data-hand="right" aria-pressed="false">Right steer</button></div><div class="setting-choices" role="group" aria-label="Touch control size"><button class="secondary-button touch-size-choice" data-size="standard" aria-pressed="true">Standard</button><button class="secondary-button touch-size-choice" data-size="large" aria-pressed="false">Large</button></div><div id="touch-preview" class="touch-preview" aria-label="Touch layout preview"><span>Steer</span><span>Boost · Skill · V</span></div><button class="secondary-button settings-reset" data-section="controls">Reset controls</button></section>
    <section id="settings-panel-appearance" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-appearance" tabindex="0" hidden><h3>Appearance</h3><button id="theme-toggle" class="secondary-button theme-toggle" aria-label="Toggle dark mode" aria-pressed="false">Dark mode: Off</button><h4>Graphics</h4><div class="setting-choices" role="group" aria-label="Graphics quality">${(["auto","low","high"] as const).map(choice => `<button class="secondary-button quality-choice" data-quality="${choice}" aria-pressed="false">${choice}</button>`).join("")}</div><button class="secondary-button settings-reset" data-section="appearance">Reset appearance</button></section>
    <section id="settings-panel-audio" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-audio" tabindex="0" hidden><h3>Audio</h3><button class="sound-toggle secondary-button" aria-label="Mute sound">Sound on</button>${(["effects", "voices"] as const).map((channel) => `<label class="volume-label" for="volume-${channel}"><span>${channel[0].toUpperCase() + channel.slice(1)}</span><output id="value-${channel}"></output></label><input id="volume-${channel}" type="range" min="0" max="100" step="1">`).join("")}<button id="voice-preview" class="secondary-button">Hear your spirit</button><button class="secondary-button settings-reset" data-section="audio">Reset audio</button><p id="audio-note" class="audio-note" role="status"></p></section>
    <section id="settings-panel-accessibility" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-accessibility" tabindex="0" hidden><h3>Accessibility</h3><h4>Motion</h4><div class="setting-choices" role="group" aria-label="Motion preference"><button class="secondary-button motion-choice" data-motion="system" aria-pressed="false">System</button><button class="secondary-button motion-choice" data-motion="reduced" aria-pressed="false">Reduced</button></div><button id="flash-toggle" class="secondary-button" aria-pressed="false">Reduced flashes: Off</button><button id="camera-toggle" class="secondary-button" aria-pressed="true">Cinematic camera: On</button><button class="secondary-button settings-reset" data-section="accessibility">Reset accessibility</button></section>
  </div>
</dialog>
<dialog id="challenges-dialog" class="sheet challenges-sheet" aria-labelledby="challenges-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">✦</span><h2 id="challenges-title">Little adventures</h2><button class="close-button" aria-label="Close challenges">×</button></div>
  <div class="sheet-scroll"><p>Play to earn body skins and boost trails. Progress is saved on this device.</p><div id="challenge-list" class="challenge-list"></div><h3>Snake skins</h3><div id="skin-choices" class="cosmetic-choices" role="group" aria-label="Snake skins"></div><h3>Boost trails</h3><div id="trail-choices" class="cosmetic-choices" role="group" aria-label="Boost trails"></div></div>
</dialog>
<dialog id="credits-dialog" class="sheet"><button class="close-button" aria-label="Close credits">×</button><span class="sheet-icon" aria-hidden="true">✦</span><h2>Made by Denz.</h2><p>Anime Coil v1.6.7 · Original procedural characters, worlds and sound effects.</p><p>Japanese speech: <b>VOICEVOX Nemo</b>. Generated locally; no voice service is needed to play.</p><p>Built with Three.js, TypeScript, and Vite. Inspired by anime adventures and cozy village games.</p></dialog>
<section id="fatal" hidden role="alert"><h2>Your spirit needs WebGL.</h2><p>Enable hardware acceleration or try a recent browser.</p><button id="reload" class="play-button">Try again</button></section>`;
