import { CHARACTERS } from "./simulation";
import { ultimateFor } from "./ultimates";
import { MODE_DESCRIPTIONS } from "./game-copy";

const coil = `<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M29 11C12-1 1 25 16 30c13 5 23-11 12-17-8-4-15 8-7 11" stroke="currentColor" stroke-width="4.5" stroke-linecap="round"/><circle cx="29" cy="11" r="3" fill="currentColor"/></svg>`;
const brand = `<div class="brand">${coil}<span>anime<span class="brand-coil">coil</span><small>MOONLIT ARENA · v1.7.3</small></span></div>`;
const settingsIcon = `<svg class="settings-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M10 2h4l.5 2.2 1.7.7 1.9-1.2 2.8 2.8-1.2 1.9.7 1.7L22 10v4l-2.2.5-.7 1.7 1.2 1.9-2.8 2.8-1.9-1.2-1.7.7L14 22h-4l-.5-2.2-1.7-.7-1.9 1.2-2.8-2.8 1.2-1.9-.7-1.7L2 14v-4l2.2-.5.7-1.7-1.2-1.9 2.8-2.8 1.9 1.2 1.7-.7L10 2zM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6z" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg>`;
const tools = `<button class="icon-button challenges-open" aria-label="Challenges and cosmetics" title="Challenges and cosmetics">✦</button><button class="icon-button help-open" aria-label="How to play" title="How to play">?</button><button class="icon-button settings-open" aria-label="Settings" title="Settings">${settingsIcon}</button>`;
export const ui = `
<canvas id="world" aria-label="3D snake arena"></canvas>
<canvas id="boost-speed-lines" aria-hidden="true"></canvas>
<div id="kill-stamps" aria-hidden="true"></div>
<div id="skill-visual" hidden role="status" aria-live="polite"><strong id="skill-japanese" lang="ja"></strong><span id="skill-label" lang="ja"></span></div>
<div id="cinematic" hidden aria-live="polite"><div class="cinema-dim"></div><div class="spirit-impact-art" aria-hidden="true"><div class="spirit-ink-rays"></div><div class="spirit-ink-contour"></div><div class="spirit-ink-core"></div></div><div class="fox-impact-art" aria-hidden="true"><div class="fox-ink-rays"></div>${Array.from({length:9},(_,i)=>`<i class="fox-ink-tail" style="--tail-angle:${i*40}deg"></i>`).join('')}<div class="fox-ink-beast"></div><div class="fox-ink-core"></div></div><div class="purple-impact-art" aria-hidden="true"><div class="purple-ink-rifts"></div><div class="purple-ink-left"></div><div class="purple-ink-right"></div><div class="purple-ink-cavity"></div><div class="purple-ink-core"></div></div><div class="skybreaker-impact-art" aria-hidden="true"><div class="skybreaker-ink-rays"></div><div class="skybreaker-ink-arm"></div><div class="skybreaker-ink-fist"></div><div class="skybreaker-ink-dent"></div><div class="skybreaker-ink-core"></div></div><div class="cinema-top"></div><div class="purple-flare"></div><div class="cinema-title"><small id="cinema-stage"></small><strong id="cinema-name">Hollow Purple</strong><span id="cinema-caption" lang="ja"></span></div><div class="cinema-bottom"></div></div>
<main id="menu"><header class="topbar">${brand}<nav aria-label="Game tools">${tools}</nav></header>
<section class="menu-content"><aside class="roster-panel" aria-labelledby="roster-title"><span class="eyebrow">CHARACTERS</span><h1 id="roster-title">Choose a character</h1><div class="characters" role="group" aria-label="Choose a character">${CHARACTERS.map((c, i) => `<button class="character" data-character="${c.id}" aria-label="Select ${c.name}" aria-pressed="${i === 0}"><img id="portrait-${c.id}" alt=""><span class="character-name">${c.name}</span><span class="selected-mark" aria-hidden="true">✓</span></button>`).join("")}</div>
</aside><section id="lobby-showcase" class="lobby-showcase" aria-label="Selected character 3D showcase"><section id="skin-preview-controls" class="skin-preview-controls" aria-label="Snake skin preview" hidden><strong id="skin-preview-name"></strong><p id="skin-preview-detail" aria-live="polite"></p><div><button id="skin-preview-back" class="secondary-button">Back to skins</button><button id="skin-preview-equip" class="secondary-button">Equip skin</button></div></section></section><div class="selection-panel"><div class="selected-spirit"><h2 id="hero-name">Kitsu</h2><button class="secondary-button character-open" aria-haspopup="dialog" aria-controls="character-dialog">Details</button></div>
<div class="section-label arena-heading"><h3>Arena</h3></div>
<section class="arena-card" aria-label="Arena: Shibuya"><img id="map-shibuya" alt=""><span>Shibuya</span></section>
<div class="section-label"><h3>Match mode</h3></div><div class="mode-picker" role="group" aria-label="Match mode"><button class="mode-choice" data-mode="endless" aria-pressed="true">Endless</button><button class="mode-choice" data-mode="sprint" aria-pressed="false">3-Min Sprint</button><button class="mode-choice" data-mode="bounty" aria-pressed="false">Bounty Hunt</button></div><p id="mode-description" class="mode-description">No time limit · Respawns</p>
<button id="play" class="play-button">Play <span aria-hidden="true">↗</span></button>
<div class="best"><span aria-hidden="true">✦</span> <span id="best-label">Personal best</span> <b id="best-score">0</b></div>
</div></section>
</main>
<div id="death-wash" aria-hidden="true"></div>
<section id="hud" hidden aria-label="Match status"><div class="hud-top"><div class="hud-score"><small id="score-label">Energy</small><strong id="score">180</strong><div class="stat-line"><span id="rank">#21</span> / <span id="population">21</span> · <span id="time">0:00</span></div><span id="hud-mode" aria-label="Endless mode">ENDLESS</span><span id="bounty-target" hidden aria-live="polite"></span></div><div class="hud-right"><div class="leaderboard"><h3>Leaderboard <span>✦</span></h3><div id="leaders"></div></div><div class="hud-actions"><button class="icon-button settings-open" aria-label="Settings">${settingsIcon}</button><button id="pause" class="icon-button" aria-label="Pause game">Ⅱ</button></div></div></div><div id="toast" hidden role="status"></div><div id="unlock-notice" hidden role="status" aria-live="polite"></div><div id="bounty-world-marker" hidden aria-hidden="true">✦</div><div id="death-contact" hidden aria-hidden="true"></div><section id="respawn-notice" class="respawn-notice" hidden role="status" aria-live="polite" aria-label="Respawning. Countdown"><span class="resting-flower" aria-hidden="true">☁</span><h2>Respawning</h2><p id="respawn-reason"></p><span id="respawn-count-label" class="respawn-count-label">Respawning in</span><strong id="respawn-count">3</strong><span id="respawn-units" class="respawn-seconds">seconds</span></section><div class="hud-bottom"><div class="mini-wrap"><canvas id="minimap" width="240" height="240" role="img" aria-label="Minimap: your arrow, rival dots, and arena boundary"></canvas></div><div class="abilities"><button id="boost" class="ability-button boost-button"><strong>Boost</strong><small id="boost-status">Hold</small><kbd>Space</kbd></button><button id="ability" class="ability-button"><strong id="ability-name">Fox Rush</strong><small id="ability-status">Ready</small><kbd>E</kbd><span class="cool-fill" id="cool-fill"></span></button><button id="nuke" hidden class="ability-button nuke-button"><strong id="ultimate-name">Hollow Purple</strong><small id="nuke-status">Ready</small><kbd>V</kbd><span class="cool-fill" id="nuke-fill"></span></button></div></div><div class="joystick" id="joystick" aria-label="Steering joystick"><span id="stick"></span></div><section id="practice-guide" hidden aria-label="Guided practice"><b id="practice-step">Step 1 / 4</b><span id="practice-instruction" aria-live="polite"></span><small id="practice-detail"></small><div><button id="practice-skip" class="secondary-button">Skip step</button><button id="practice-exit" class="secondary-button">Leave practice</button></div></section></section>
<section id="pause-modal" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="pause-title"><div class="modal-card pause-card">
  <div class="modal-flower" aria-hidden="true">☁</div><h2 id="pause-title">Paused</h2><p>The match is paused. Resume to continue.</p>
  <button id="resume" class="play-button">Resume <span aria-hidden="true">↗</span></button>
  <div class="pause-tools">${tools}</div>
  <div class="pause-actions"><button id="end-recap" class="secondary-button">End run &amp; recap</button><button id="quit" class="secondary-button quiet-button">Back to lobby</button></div>
</div></section>
<section id="results" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="results-title"><div class="modal-card results-card">
  <div class="modal-header"><span class="sheet-icon" aria-hidden="true">✿</span><h2 id="results-title">Run complete</h2></div>
  <div class="modal-scroll"><p id="death-reason"></p><p id="result-record" class="result-record"></p>
    <div class="results-grid"><div><strong id="result-score">0</strong><small id="result-score-label">Peak energy</small></div><div><strong id="result-time">0:00</strong><small>Time played</small></div><div><strong id="result-kills">0</strong><small>Eliminations</small></div></div>
    <p id="bounty-results" hidden></p><p id="session-progress" class="session-progress"></p><p id="session-unlocks" class="session-unlocks"></p>
    <div class="result-actions"><button id="restart" class="play-button">Play again <span aria-hidden="true">↗</span></button><button id="result-challenges" class="secondary-button challenges-open">View challenges</button><button id="change" class="secondary-button quiet-button">Choose a character</button></div>
  </div>
</div></section>
<dialog id="help-dialog" class="sheet" aria-labelledby="help-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">?</span><h2 id="help-title">How to play</h2><button class="close-button" aria-label="Close help">×</button></div>
  <div class="sheet-scroll"><p class="help-intro">Collect energy orbs to grow your snake. Avoid other snakes’ heads and bodies and stay inside the arena boundary. You can cross your own body safely. Move the mouse to steer, or use the joystick on touch screens.</p>
    <div class="control-guide"><span><kbd>Mouse</kbd><span>Steer</span></span><span><kbd id="help-boost-key">Space</kbd><span>/ click Boost · spends energy</span></span><span><kbd id="help-ability-key">E</kbd><span>/ right-click · Use skill</span></span><span><kbd id="help-ultimate-key">V</kbd><span>Use ultimate</span></span><span><kbd>Esc</kbd><span>Pause</span></span></div>
    <p class="touch-guide">Normal Boost moves you 70% faster and spends 24 energy per second. It stops at minimum energy. On touch screens, steer with the joystick and tap the ability buttons.</p><button id="practice-start" class="secondary-button practice-button">Try guided practice</button>
    <details class="help-details"><summary>Match modes</summary>${Object.entries(MODE_DESCRIPTIONS).map(([mode, description]) => `<p><b>${({endless:'Endless', sprint:'3-Min Sprint', bounty:'Bounty Hunt', practice:'Practice'} as const)[mode as keyof typeof MODE_DESCRIPTIONS]}.</b> ${description}</p>`).join("")}</details>
    <details class="help-details"><summary>Character skills</summary><div class="help-skills">${CHARACTERS.map((c) => `<article><h3>${c.name}<span>${c.cooldown}s cooldown</span></h3><p><b>${c.power}.</b> ${c.description}</p></article>`).join("")}</div></details>
    <details class="help-details"><summary>Ultimates</summary><div class="help-skills">${CHARACTERS.map(c => { const u = ultimateFor(c.id); return `<article><h3>${c.name}: ${u.name}<span>${u.duration}s attack · ${u.cooldown}s cooldown</span></h3><p>${u.description}</p></article>`; }).join("")}</div></details>
  </div>
</dialog>
<dialog id="character-dialog" class="sheet character-sheet" aria-labelledby="character-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">✦</span><h2 id="character-title">Kitsu abilities</h2><button class="close-button" aria-label="Close character details">×</button></div>
  <div class="sheet-scroll"><article><span class="skill-badge"><kbd id="menu-ability-key">E</kbd><span id="power-name">Fox Rush</span></span><p id="hero-description"></p><small id="ability-cooldown"></small></article><article><span id="purple-badge" class="skill-badge purple" hidden><kbd id="menu-ultimate-key">V</kbd><span id="ultimate-badge-name">Fox Spirit Bomb</span></span><p id="ultimate-description"></p><small id="ultimate-timing"></small></article></div>
</dialog>
<dialog id="settings-dialog" class="sheet settings-sheet" aria-labelledby="settings-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">⚙</span><h2 id="settings-title">Settings</h2><button class="close-button" aria-label="Close settings">×</button></div>
  <div class="settings-tabs" role="tablist" aria-label="Settings sections">
    <button id="settings-tab-controls" role="tab" aria-selected="true" aria-controls="settings-panel-controls" tabindex="0" data-settings-tab="controls">Controls</button>
    <button id="settings-tab-appearance" role="tab" aria-selected="false" aria-controls="settings-panel-appearance" tabindex="-1" data-settings-tab="appearance">Appearance</button>
    <button id="settings-tab-audio" role="tab" aria-selected="false" aria-controls="settings-panel-audio" tabindex="-1" data-settings-tab="audio">Audio</button>
    <button id="settings-tab-accessibility" role="tab" aria-selected="false" aria-controls="settings-panel-accessibility" tabindex="-1" data-settings-tab="accessibility">Accessibility</button>
  </div>
  <div class="sheet-scroll settings-scroll">
    <section id="settings-panel-controls" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-controls" tabindex="0"><h3>Controls</h3><div class="binding-list">${(["boost","ability","ultimate"] as const).map(action => `<button class="secondary-button key-binding" data-action="${action}" aria-label="Change ${action} key"><span>${action}</span><kbd></kbd></button>`).join("")}</div><p id="binding-note" role="status">Select a control, then press a letter, number, or Space.</p><h4>Touch layout</h4><div class="setting-choices" role="group" aria-label="Touch handedness"><button class="secondary-button touch-hand-choice" data-hand="left" aria-pressed="true">Left steer</button><button class="secondary-button touch-hand-choice" data-hand="right" aria-pressed="false">Right steer</button></div><div class="setting-choices" role="group" aria-label="Touch control size"><button class="secondary-button touch-size-choice" data-size="standard" aria-pressed="true">Standard</button><button class="secondary-button touch-size-choice" data-size="large" aria-pressed="false">Large</button></div><div id="touch-preview" class="touch-preview" aria-label="Touch layout preview"><span>Steer</span><span>Boost · Skill · V</span></div><button class="secondary-button settings-reset" data-section="controls">Reset controls</button></section>
    <section id="settings-panel-appearance" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-appearance" tabindex="0" hidden><h3>Appearance</h3><h4>Graphics</h4><div class="setting-choices" role="group" aria-label="Graphics quality">${(["auto","low","high"] as const).map(choice => `<button class="secondary-button quality-choice" data-quality="${choice}" aria-pressed="false">${choice}</button>`).join("")}</div><button class="secondary-button settings-reset" data-section="appearance">Reset appearance</button></section>
    <section id="settings-panel-audio" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-audio" tabindex="0" hidden><h3>Audio</h3><button class="sound-toggle secondary-button" aria-label="Mute sound">Sound on</button>${(["effects", "voices"] as const).map((channel) => `<label class="volume-label" for="volume-${channel}"><span>${channel[0].toUpperCase() + channel.slice(1)}</span><output id="value-${channel}"></output></label><input id="volume-${channel}" type="range" min="0" max="100" step="1">`).join("")}<button id="voice-preview" class="secondary-button">Preview character voice</button><button class="secondary-button settings-reset" data-section="audio">Reset audio</button><p id="audio-note" class="audio-note" role="status"></p></section>
    <section id="settings-panel-accessibility" class="settings-section" role="tabpanel" aria-labelledby="settings-tab-accessibility" tabindex="0" hidden><h3>Accessibility</h3><h4>Motion</h4><div class="setting-choices" role="group" aria-label="Motion preference"><button class="secondary-button motion-choice" data-motion="system" aria-pressed="false">System</button><button class="secondary-button motion-choice" data-motion="reduced" aria-pressed="false">Reduced</button></div><button id="flash-toggle" class="secondary-button" aria-pressed="false">Reduced flashes: Off</button><button id="camera-toggle" class="secondary-button" aria-pressed="true">Cinematic camera: On</button><button class="secondary-button settings-reset" data-section="accessibility">Reset accessibility</button></section>
    <button class="secondary-button credits-open settings-credits">Credits</button>
  </div>
</dialog>
<dialog id="challenges-dialog" class="sheet challenges-sheet" aria-labelledby="challenges-title">
  <div class="sheet-header"><span class="sheet-icon" aria-hidden="true">✦</span><h2 id="challenges-title">Challenges & cosmetics</h2><button class="close-button" aria-label="Close challenges">×</button></div>
  <div class="sheet-scroll"><p>Play to earn body skins and boost trails. Progress is saved on this device.</p><div id="challenge-list" class="challenge-list"></div><h3>Snake skins</h3><div id="skin-choices" class="cosmetic-choices" role="group" aria-label="Snake skins"></div><h3>Boost trails</h3><div id="trail-choices" class="cosmetic-choices" role="group" aria-label="Boost trails"></div></div>
</dialog>
<dialog id="credits-dialog" class="sheet"><button class="close-button" aria-label="Close credits">×</button><span class="sheet-icon" aria-hidden="true">✦</span><h2>Made by Denz.</h2><p>Anime Coil v1.7.3 · Custom characters, Blender Kitsu sculpture, Shibuya arena and sound effects.</p><p>Japanese speech: <b>VOICEVOX Nemo</b>. Generated locally; no voice service is needed to play.</p><p>Built with Three.js, TypeScript, and Vite. The arena and game run locally in your browser.</p></dialog>
<section id="fatal" hidden role="alert"><h2>3D graphics are unavailable.</h2><p>Enable hardware acceleration or try a recent browser.</p><button id="reload" class="play-button">Try again</button></section>`;
