import { CHARACTERS } from "./simulation";
import { MAPS } from "./maps";

const coil = `<svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><path d="M29 11C12-1 1 25 16 30c13 5 23-11 12-17-8-4-15 8-7 11" stroke="currentColor" stroke-width="4.5" stroke-linecap="round"/><circle cx="29" cy="11" r="3" fill="currentColor"/></svg>`;
const brand = `<div class="brand">${coil}<span>anime<span class="brand-coil">coil</span><small>LIVING WORLDS · v1.4.0</small></span></div>`;
const musicIcon = `<svg class="music-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M12 3v12.25a3.75 3.75 0 1 1-2-3.32V6.5l10-2.25v10a3.75 3.75 0 1 1-2-3.32V6.75L12 8.1V3z"/></svg>`;
const tools = `<button class="icon-button challenges-open" aria-label="Challenges and cosmetics" title="Challenges and cosmetics">✦</button><button class="icon-button help-open" aria-label="How to play" title="How to play">?</button><button class="icon-button settings-open" aria-label="Audio settings" title="Audio settings">${musicIcon}</button>`;
export const ui = `
<canvas id="world" aria-label="3D spirit serpent arena"></canvas>
<canvas id="boost-speed-lines" aria-hidden="true"></canvas>
<div id="kill-stamps" aria-hidden="true"></div>
<div id="skill-visual" hidden role="status" aria-live="polite"><strong id="skill-japanese" lang="ja"></strong><span id="skill-label" lang="ja"></span></div>
<div id="cinematic" hidden aria-live="polite"><div class="cinema-dim"></div><div class="cinema-top"></div><div class="purple-flare"></div><div class="cinema-title"><small id="cinema-stage"></small><strong id="cinema-name">Hollow Purple</strong><span id="cinema-caption" lang="ja"></span></div><div class="cinema-bottom"></div></div>
<main id="menu"><header class="topbar">${brand}<nav aria-label="Game tools">${tools}</nav></header>
<section class="menu-content"><div class="selection-panel">
<div class="panel-heading"><span class="leaf" aria-hidden="true">✿</span><h1>Pick your little legend.</h1></div>
<div class="characters" role="group" aria-label="Choose your spirit">${CHARACTERS.map((c, i) => `<button class="character" data-character="${c.id}" aria-label="Select ${c.name}" aria-pressed="${i === 0}"><img id="portrait-${c.id}" alt="${c.name}"><span class="selected-mark" aria-hidden="true">✓</span></button>`).join("")}</div>
<div class="selected-spirit"><h2 id="hero-name">Kitsu</h2><span class="skill-badge"><kbd>E</kbd><span id="power-name">Fox Rush</span></span><span id="purple-badge" class="skill-badge purple" hidden><kbd>V</kbd><span id="ultimate-badge-name">Hollow Purple</span></span></div>
<div class="section-label"><h3>A little change of scenery</h3><span aria-hidden="true">↗</span></div>
<div class="maps" role="group" aria-label="Choose your map">${MAPS.map((m) => `<button class="map-card" data-map="${m.id}" aria-label="Select ${m.name}" aria-pressed="false"><img id="map-${m.id}" alt="${m.name}"><span>${m.shortName}</span></button>`).join("")}</div>
<div class="mode-picker" role="group" aria-label="Match mode"><button class="mode-choice" data-mode="endless" aria-pressed="true">Endless</button><button class="mode-choice" data-mode="sprint" aria-pressed="false">3-Min Sprint</button></div>
<button id="play" class="play-button">Let's play <span aria-hidden="true">↗</span></button>
<div class="best"><span aria-hidden="true">✦</span> <span id="best-label">Personal best</span> <b id="best-score">0</b></div>
</div><div class="preview-label"><span aria-hidden="true">⌁</span><span id="map-preview-name">Shibuya After Dark</span></div><section id="skin-preview-controls" class="skin-preview-controls" aria-label="Snake skin preview" hidden><strong id="skin-preview-name"></strong><p id="skin-preview-detail" aria-live="polite"></p><div><button id="skin-preview-back" class="secondary-button">Back to skins</button><button id="skin-preview-equip" class="secondary-button">Equip skin</button></div></section></section>
<footer class="menu-footer"><button class="text-button credits-open">Credits</button></footer></main>
<div id="death-wash" aria-hidden="true"></div>
<section id="hud" hidden aria-label="Match status"><div class="hud-top"><div class="hud-score"><small>Energy</small><strong id="score">180</strong><div class="stat-line"><span id="rank">#21</span> / <span id="population">21</span> · <span id="time">0:00</span></div><span id="hud-mode" aria-label="Endless mode">ENDLESS</span></div><div class="hud-right"><div class="leaderboard"><h3>Top spirits <span>✦</span></h3><div id="leaders"></div></div><div class="hud-actions"><button class="icon-button settings-open" aria-label="Audio settings">${musicIcon}</button><button id="pause" class="icon-button" aria-label="Pause game">Ⅱ</button></div></div></div><div id="toast" hidden role="status"></div><section id="respawn-notice" class="respawn-notice" hidden role="status" aria-live="polite" aria-label="Spirit resting. Respawn countdown"><span class="resting-flower" aria-hidden="true">☁</span><h2>Spirit resting</h2><p id="respawn-reason"></p><span class="respawn-count-label">Returning in</span><strong id="respawn-count">3</strong><span id="respawn-units" class="respawn-seconds">seconds</span></section><div class="hud-bottom"><div class="mini-wrap"><canvas id="minimap" width="240" height="240" role="img" aria-label="Spirit compass: your arrow, rival dots, and arena boundary"></canvas></div><div class="abilities"><button id="boost" class="ability-button boost-button"><strong>Boost</strong><small id="boost-status">Hold</small><kbd>Space</kbd></button><button id="ability" class="ability-button"><strong id="ability-name">Fox Rush</strong><small id="ability-status">Ready</small><kbd>E</kbd><span class="cool-fill" id="cool-fill"></span></button><button id="nuke" hidden class="ability-button nuke-button"><strong id="ultimate-name">Hollow Purple</strong><small id="nuke-status">Ready</small><kbd>V</kbd><span class="cool-fill" id="nuke-fill"></span></button></div></div><div class="joystick" id="joystick" aria-label="Steering joystick"><span id="stick"></span></div><section id="practice-guide" hidden aria-label="Guided practice"><b id="practice-step">Step 1 / 4</b><span id="practice-instruction" aria-live="polite"></span><small id="practice-detail"></small><div><button id="practice-skip" class="secondary-button">Skip step</button><button id="practice-exit" class="secondary-button">Leave practice</button></div></section></section>
<section id="pause-modal" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="pause-title"><div class="modal-card"><div class="modal-flower" aria-hidden="true">☁</div><h2 id="pause-title">A little breather.</h2><p>Your adventure can wait.</p><button id="resume" class="play-button">Keep playing <span>↗</span></button><div class="pause-tools">${tools}</div><button id="quit" class="secondary-button">Back to the garden</button></div></section>
<section id="results" class="modal" hidden role="dialog" aria-modal="true" aria-labelledby="results-title"><div class="modal-card"><div class="modal-flower" aria-hidden="true">✿</div><h2 id="results-title">One more adventure?</h2><p id="death-reason"></p><p id="result-record" class="result-record"></p><div class="results-grid"><div><strong id="result-score">0</strong><small>Best energy</small></div><div><strong id="result-time">0:00</strong><small>Time</small></div><div><strong id="result-kills">0</strong><small>Rivals</small></div></div><button id="restart" class="play-button">Play again <span>↗</span></button><button id="change" class="secondary-button">Choose a spirit</button></div></section>
<dialog id="help-dialog" class="sheet"><button class="close-button" aria-label="Close help">×</button><span class="sheet-icon" aria-hidden="true">?</span><h2>A tiny field guide</h2><p>Gather glowing energy to grow. Avoid other heads, rival coils, and the arena edge. Your own tail is safe.</p><div class="control-guide"><span><kbd>Mouse</kbd> Steer</span><span><kbd>Space / click</kbd> Boost · spends energy</span><span><kbd>E / right-click</kbd> Skill</span><span><kbd>V</kbd> Spirit form or ultimate</span><span><kbd>Esc</kbd> Pause</span></div><p class="touch-guide">On touch screens, use the joystick and skill buttons.</p><button id="practice-start" class="secondary-button">Try guided practice</button><div class="help-skills">${CHARACTERS.map((c) => `<article><h3>${c.name}<span>${c.cooldown}s cooldown</span></h3><p><b>${c.power}.</b> ${c.description}</p></article>`).join("")}<article><h3>Kitsu: Nine-Tail Cloak <span>V · 8s · 30s cooldown</span></h3><p>Gain mass-free boost and a brief rival-collision shield. Kitsu's head contact eliminates rivals; the arena edge remains dangerous.</p></article><article><h3>Pomu: Skybreaker Barrage <span>V · 8s · 30s cooldown</span></h3><p>Fire a focused forward punch every 0.65 seconds. Each punch can eliminate one rival; steer to aim each attack. The form does not pull, freeze, or wipe the arena.</p></article><article><h3>Hollow Purple <span>V · 5.6s · 30s cooldown</span></h3><p>Shiro's cinematic ultimate pulls in every rival before the blast. You stay safe; every rival falls. New bots appear afterward.</p></article><article><h3>Spirit Bomb <span>V · 5.6s · 30s cooldown</span></h3><p>Kairo freezes rivals in place, gathers energy overhead, and throws a giant Spirit Bomb that wipes the arena clean. You stay safe; bots return after the blast.</p></article></div></dialog>
<dialog id="settings-dialog" class="sheet settings-sheet"><button class="close-button" aria-label="Close audio settings">×</button><span class="sheet-icon" aria-hidden="true">♫</span><h2>Sounds like a good day.</h2><button class="sound-toggle secondary-button" aria-label="Mute sound">Sound on</button><button id="theme-toggle" class="secondary-button theme-toggle" aria-label="Toggle dark mode" aria-pressed="false">Dark mode: Off</button>${(["effects", "voices"] as const).map((channel) => `<label class="volume-label" for="volume-${channel}"><span>${channel[0].toUpperCase() + channel.slice(1)}</span><output id="value-${channel}"></output></label><input id="volume-${channel}" type="range" min="0" max="100" step="1">`).join("")}<button id="voice-preview" class="secondary-button">Hear your spirit</button><p id="audio-note" class="audio-note" role="status"></p></dialog>
<dialog id="challenges-dialog" class="sheet challenges-sheet"><button class="close-button" aria-label="Close challenges">×</button><span class="sheet-icon" aria-hidden="true">✦</span><h2>Little adventures</h2><p>Play to earn body skins and boost trails.</p><div id="challenge-list" class="challenge-list"></div><h3>Snake skins</h3><div id="skin-choices" class="cosmetic-choices" role="group" aria-label="Snake skins"></div><h3>Boost trails</h3><div id="trail-choices" class="cosmetic-choices" role="group" aria-label="Boost trails"></div></dialog>
<dialog id="credits-dialog" class="sheet"><button class="close-button" aria-label="Close credits">×</button><span class="sheet-icon" aria-hidden="true">✦</span><h2>Made by Denz.</h2><p>Anime Coil v1.4.0 · Original procedural characters, worlds and sound effects.</p><p>Japanese speech: <b>VOICEVOX Nemo</b>. Generated locally; no voice service is needed to play.</p><p>Built with Three.js, TypeScript, and Vite. Inspired by anime adventures and cozy village games.</p></dialog>
<section id="fatal" hidden role="alert"><h2>Your spirit needs WebGL.</h2><p>Enable hardware acceleration or try a recent browser.</p><button id="reload" class="play-button">Try again</button></section>`;
